//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Terra.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TerraParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ITerraListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] TerraParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] TerraParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] TerraParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] TerraParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] TerraParser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] TerraParser.IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] TerraParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] TerraParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.pathExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathExpression([NotNull] TerraParser.PathExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.pathExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathExpression([NotNull] TerraParser.PathExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.fileName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileName([NotNull] TerraParser.FileNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.fileName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileName([NotNull] TerraParser.FileNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] TerraParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] TerraParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.window"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindow([NotNull] TerraParser.WindowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.window"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindow([NotNull] TerraParser.WindowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] TerraParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] TerraParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TerraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] TerraParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TerraParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] TerraParser.StatementContext context);
}
